### ISSUE TITLE
Fix doi link checking for newly created blog posts

### ISSUE THREAD

**Issue by mfenner** [datacite/blog#115]

**Comment by richardhallett** [comment]
One solution is to not check doi.org urls, you can add ignores to htmlproofer via:
--url-ignore=/doi.org/

**Comment by mfenner** [comment]
You can also disable checking for specific links:

```
<a href="http://notareallink" data-proofer-ignore>Not checked.</a>
```

**Comment by mfenner** [comment]
And also in https://github.com/datacite/blog/blob/master/source/includes/_infobox.html.erb#L15.

**Comment by richardhallett** [comment]
For all DOI links added :
`"data-proofer-ignore" => true`
Note that middlemans link_to helper doesn't seem to support empty attributes, but a true value attribute works as well.
