### ISSUE TITLE
Blog results should be based on the published date of the metadata

### ISSUE THREAD

**Issue by richardhallett** [datacite/blog#122]
The sort on the datacite blog: blog.datacite.org is using created date of the DOI rather than the date of the published article, this should ideally be same as what is displayed.

calls:
https://api.datacite.org/dois?page%5Bsize%5D=10&page%5Bnumber%5D=1&client-id=datacite.blog&sort=-created&state=findable

Potential fix is to just use a custom query against one of the dates in the metadata.

**Comment by mfenner** [comment]
As `publicationYear` is not granular enough, I suggest `date issued`.

**Comment by mfenner** [comment]
Implemented changes. Needs re-indexing, which will not happen immediately for the production system. Once re-indexed, `sort=published` and `sort=-published` will be supported.

**Comment by mfenner** [comment]
This is now deployed in our test system, i.e. https://api.test.datacite.org/dois?sort=-published is supported.
