### ISSUE TITLE
Missing metadata for dates causes blog search to break.

### ISSUE THREAD

**Issue by richardhallett** [datacite/blog#170]
Dates is a required piece of metadata for parsing the DOI search screen, if it is missing in any of the dois the search breaks.

In addition the blog pages dont appear to have any dates added as part of the schema.org metadata so auto population of metadata in fabrica doesn't pick this up, thus exposing the problem.

**Comment by mfenner** [comment]
Fixed by @richardhallett via https://github.com/datacite/blog/commit/c6923155362893e23fc4b498699b0b3fcdf1840a
